version: "3"

services:
  postgres:
    image: postgres
    tty: true
    restart: always
    ports:
      - "5432:5432"
    environment:
      # PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      # - .:/var/lib/postgresql/data